#!/usr/bin/env bash

REPO="eighth-inning"
DIR="/usr/local/opt/${REPO}"
GITHUB_USER="chrisopedia"

# Success logging
_success() {
	printf "$(tput setaf 2)✓ Success:$(tput sgr0) %s\n" "$@"
}

# Command/Processing logging
_process() {
	printf "$(tput setaf 6)┃$(tput sgr0)$(tput setaf 7) %s...$(tput sgr0)\n" "$@"
}

# Check for Homebrew; install brew
if ! type -P 'brew' &> /dev/null; then
	ruby -e "$(curl -#fkL raw.github.com/Homebrew/homebrew/go/install)"

	_process "Running brew doctor"
	brew doctor

	brew install terminal-notifier
	brew linkapps --local

	[[ $? ]] && _success "Homebrew installed"
fi

# If missing, download and extract the repository
if [[ ! -d "${DIR}" ]]; then

	# No directory found
	printf "%s⚠ Warning:%s No %s found!\n" "$(tput bold ; tput setaf 3)" "$(tput sgr0)" "${DIR}"

	# Create directory
	printf "%s┃%s Creating directory at %s...%s\n" "$(tput setaf 6)" "$(tput sgr0 ; tput setaf 7)" "${DIR}" "$(tput sgr0)"
	mkdir -p "${DIR}"

	# Download the repository as a tarball
	printf "%s┃%s Downloading repository to /tmp directory...%s\n" "$(tput setaf 6)" "$(tput sgr0 ; tput setaf 7)" "$(tput sgr0)"
	curl -#fLo /tmp/${REPO}.tar.gz "https://github.com/${GITHUB_USER}/${REPO}/tarball/master"

	# Extract to the ${REPO} directory
	printf "%s┃%s Extracting files to %s...%s\n" "$(tput setaf 6)" "$(tput sgr0 ; tput setaf 7)" "${DIR}" "$(tput sgr0)"
	tar -zxf /tmp/${REPO}.tar.gz --strip-components 1 -C "${DIR}"

	# Remove the tarball
	printf "%s┃%s Removing tarball from /tmp directory...%s\n" "$(tput setaf 6)" "$(tput sgr0 ; tput setaf 7)" "$(tput sgr0)"
	rm -rf /tmp/${REPO}.tar.gz

	printf "%s✓ Success:%s %s created, repository downloaded and extracted.\n" "$(tput setaf 2)" "$(tput sgr0)" "${DIR}"
fi

# Symlink library files
_process "Symlinking dotfiles command & man page"
ln -fs "${DIR}/bin/${REPO}" "/usr/local/bin/${REPO}"

[[ $? ]] && printf "%s✓ Success:%s %s has been installed.%s\n" "$(tput setaf 2)" "$(tput sgr0 ; tput setaf 7)" "${DIR}" "$(tput sgr0)"
